#!/usr/bin/env bash

# Install non-Rust dependencies on Debian-based distributions like this:
# > sudo apt-get update
# > sudo apt-get install  \
# >     cmake             \
# >     libssl-dev        \
# >     pkg-config        \
# >     silversearcher-ag \
# >     zlib1g-dev

set -o errexit

export PATH="${CARGO_HOME:-$HOME/.cargo}/bin:$PATH"

curl               \
    --fail         \
    --proto =https \
    --show-error   \
    --silent       \
    --tlsv1.2      \
    https://sh.rustup.rs > rustup-init.sh

# rustup-init.sh specifies Bash as the interpreter in its shebang line.
# See https://github.com/rust-lang/rustup.rs/blob/9c7f3136eae9891e8a44b885000bb20fb911dea2/rustup-init.sh.
bash rustup-init.sh --no-modify-path -y

rustup component add clippy rustfmt

# Cargo has no built-in way to update installed binary crates.
# A command for it was recently implemented but hasn't been released yet.
# See https://github.com/rust-lang/cargo/issues/6797.
if ! command -v cargo-install-update
then
    cargo install cargo-update
fi
cargo install-update --allow-no-update cargo-tarpaulin cargo-update

cargo update --locked
cargo fmt --all -- --check
cargo clippy                                      \
    --profile test                                \
    --                                            \
    --warn absolute_paths_not_starting_with_crate \
    --warn deprecated_in_future                   \
    --warn macro_use_extern_crate                 \
    --warn trivial_casts                          \
    --warn trivial_numeric_casts                  \
    --warn unsafe_code                            \
    --warn unused_labels                          \
    --warn unused_lifetimes                       \
    --warn unused_qualifications                  \
    --warn clippy::nursery                        \
    --warn clippy::pedantic                       \
    --warn clippy::clone_on_ref_ptr               \
    --warn clippy::dbg_macro                      \
    --warn clippy::decimal_literal_representation \
    --warn clippy::float_arithmetic               \
    --warn clippy::float_cmp_const                \
    --warn clippy::get_unwrap                     \
    --warn clippy::mem_forget                     \
    --warn clippy::multiple_inherent_impl         \
    --warn clippy::option_unwrap_used             \
    --warn clippy::print_stdout                   \
    --warn clippy::result_unwrap_used             \
    --warn clippy::string_add                     \
    --warn clippy::unimplemented                  \
    --warn clippy::use_debug                      \
    --warn clippy::wrong_pub_self_convention      \
    --deny warnings

tarpaulin() {
    cargo tarpaulin    \
        --ignore-tests \
        --out Xml      \
        --verbose
}

# Tarpaulin exits successfully (with zero status) if any of the tests segfault.
# We work around that by searching Tarpaulin's output for error messages and
# making the build fail if we find any.
! tarpaulin |& ag --passthrough ERROR